In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"/content/Suppy_Chain_Shipment_Data.csv")

In [ ]:
df.shape

(10324, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            10324 non-null  int64
 1   project code                  10324 non-null  object
 2   pq #                          10324 non-null  object
 3   po / so #                     10324 non-null  object
 4   asn/dn #                      10324 non-null  object
 5   country                       10324 non-null  object
 6   managed by                    10324 non-null  object
 7   fulfill via                   10324 non-null  object
 8   vendor inco term              10324 non-null  object
 9   shipment mode                 9964 non-null   object
 10  pq first sent to client date  10324 non-null  object
 11  po sent to vendor date        10324 non-null  object
 12  scheduled delivery date       10324 non-null  object
 13  delivered to client date      10324 non-null  object
 14  delivery recorded date        10324 non-null  object
 15  product group                 10324 non-null  object
 16  sub classification            10324 non-null  object
 17  vendor                        10324 non-null  object
 18  item description              10324 non-null  object
 19  molecule/test type            10324 non-null  object
 20  brand                         10324 non-null  object
 21  dosage                        8588 non-null   object
 22  dosage form                   10324 non-null  object
 23  unit of measure (per pack)    10324 non-null  int64
 24  line item quantity            10324 non-null  int64
 25  line item value               10324 non-null  float64
 26  pack price                    10324 non-null  float64
 27  unit price                    10324 non-null  float64
 28  manufacturing site            10324 non-null  object
 29  first line designation        10324 non-null  bool
 30  weight (kilograms)            10324 non-null  object
 31  freight cost (usd)            10324 non-null  object
 32  line item insurance (usd)     10037 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(25)
memory usage: 2.5+ MB

In [ ]:
df.describe()

,id,unit of measure (per pack),line item quantity,line item value,pack price,unit price,line item insurance (usd)
count,10324.000000,10324.000000,10324.000000,1.032400e+04,10324.000000,10324.000000,10037.000000
mean,51098.968229,77.990895,18332.534870,1.576506e+05,21.910241,0.611701,240.117626
std,31944.332496,76.579764,40035.302961,3.452921e+05,45.609223,3.275808,500.190568
min,1.000000,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,12795.750000,30.000000,408.000000,4.314593e+03,4.120000,0.080000,6.510000
50%,57540.500000,60.000000,3000.000000,3.047147e+04,9.300000,0.160000,47.040000
75%,83648.250000,90.000000,17039.750000,1.664471e+05,23.592500,0.470000,252.400000
max,86823.000000,1000.000000,619999.000000,5.951990e+06,1345.640000,238.650000,7708.440000

In [ ]:
df.isnull().sum()

id                                 0
project code                       0
pq #                               0
po / so #                          0
asn/dn #                           0
country                            0
managed by                         0
fulfill via                        0
vendor inco term                   0
shipment mode                    360
pq first sent to client date       0
po sent to vendor date             0
scheduled delivery date            0
delivered to client date           0
delivery recorded date             0
product group                      0
sub classification                 0
vendor                             0
item description                   0
molecule/test type                 0
brand                              0
dosage                          1736
dosage form                        0
unit of measure (per pack)         0
line item quantity                 0
line item value                    0
pack price                         0
unit price                         0
manufacturing site                 0
first line designation             0
weight (kilograms)                 0
freight cost (usd)                 0
line item insurance (usd)        287
dtype: int64

In [ ]:
Product (item description, commodity);
Product group
Sub Classification
Item description
Molecule/test type
Brand
Dosage
Dosage form
Unit of measure(per pack)
Manufacturing Site

In [ ]:
Supplier (vendor name or ID);
vendor inco term
Vendor
ID

In [ ]:
Order dates (date PO was raised);
pq first sent to client date
po sent to vendor date

In [ ]:
Delivery / shipment dates;
scheduled delivery date
delivered to client date
delivery recorded date

In [ ]:
Quantities (units ordered, units delivered);
dosage
unit of measure (per pack)
line item quantity
line item value

In [ ]:
Other Columns:

In [ ]:
The column(s) affected;

In [ ]:
The type of issue (missing values, inconsistent format, duplicates, outliers, etc.)

In [ ]:
Why it matters for analysis